# Code example of Symbolic Sampling for Max-Clique

In [3]:
# make sure autoqubo is also installed in this jupyter kernel
%cd ../..
%pip install -e .
%cd examples/max_clique

c:\Users\A200232161\projects\autoqubo_update
Obtaining file:///C:/Users/A200232161/projects/autoqubo_update
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Attempting uninstall: autoqubo
    Found existing installation: autoqubo 0.0.1
    Uninstalling autoqubo-0.0.1:
      Successfully uninstalled autoqubo-0.0.1
  Running setup.py develop for autoqubo
Note: you may need to restart the kernel to use updated packages.
c:\Users\A200232161\projects\autoqubo_update\examples\max_clique


In [4]:
import pandas as pd
import numpy as np
from itertools import combinations
from pathlib import Path

from autoqubo import SamplingCompiler

### Helper functions to parse Max-Clique instances


In [5]:
# make DIMACS files accessible
DATASET_PATH = "..//data/max_clique_dimacs_subset/"


instances_200 = [
    "c-fat200-1.clq",
    "c-fat200-2.clq",
    "brock200_1.clq",
    "brock200_2.clq",
    "brock200_3.clq",
    "san200_0.7_1.clq",
    "san200_0.7_2.clq",
    "san200_0.9_1.clq",
    "san200_0.9_2.clq",
    "san200_0.9_3.clq",
]
BATCH_SMALL = [Path().joinpath(DATASET_PATH + fn) for fn in instances_200]


def read_graph(file_path):
    """reads edge set from DIMACS graph
    Args:
        file_path(os.PathLike): path to dimacs formatted textfile
    Returns:
        edges(np.ndarray): adjacency matrix,  edges[v1, v2]==1 iff v1, v2 are adjacent
        vertices_num(int): number of vertices
    """
    last_vertex_has_edge = False
    with open(file_path, encoding="utf-8") as graph_file:
        for i, line in enumerate(graph_file):
            if i == 0:
                instance_name = str(Path(file_path).stem)
                print(f"Reading graph: {instance_name}")
            elif line.startswith("p"):
                _, _, vertices_num, edges_num = line.split()
                vertices_num = int(vertices_num)
                print(f"Vertices: {vertices_num}, Edges: {edges_num}")
                edges = np.zeros(shape=(vertices_num, vertices_num))
            elif line.startswith("e"):
                _, temp_1, temp_2 = line.split()
                if temp_1 == temp_2:
                    continue
                # only save one pair (i,j) per edge, i<j
                temp_1 = int(temp_1)
                temp_2 = int(temp_2)
                node_1 = min(temp_1, temp_2) - 1  # node names start with 1
                node_2 = max(temp_1, temp_2) - 1
                assert node_2 <= vertices_num, "specified number of nodes is incorrect"
                if node_2 == vertices_num - 1:
                    last_vertex_has_edge = True
                edges[node_1, node_2] = 1
            elif line.startswith("c"):  # ignore comment lines
                continue
            else:
                raise ValueError("unknown line in dimacs graph file: ", line)
    if not last_vertex_has_edge:
        raise ValueError(
            "number of vertices does not match edge set. last vertex has no edges."
        )
    return edges, vertices_num

#### Explicit Sampling

In [6]:
# explicit-only constraint function
def old_constraint(x, edges):
    """returns number of constraint violations"""
    sum_violations = 0
    for i, j in combinations(range(len(x)), 2):
        edge = edges[i, j]
        if (x[i] == 1 and x[j] == 1) and edge == 0:
            sum_violations += 1
    return sum_violations

def cost_function(x):
    """maximize clique size"""
    return -1 * sum(x)

In [7]:
# load example max clique instance
filename = BATCH_SMALL[0]
edges, n = read_graph(filename)

Reading graph: c-fat200-1
Vertices: 200, Edges: 1534


In [8]:
# explicit constraint function defined by given graph
explicit_constraint = lambda x: old_constraint(x, edges)

In [9]:
# obtain explicit QUBO
qubo1, offset = SamplingCompiler.generate_qubo(
    cost_function, explicit_constraint, n, penalty_method="sum"
)

In [10]:
# QUBO matrix only has numeric entries
qubo1

array([[ -1.,   0., 200., ..., 200., 200., 200.],
       [  0.,  -1.,   0., ..., 200., 200., 200.],
       [  0.,   0.,  -1., ..., 200., 200., 200.],
       ...,
       [  0.,   0.,   0., ...,  -1.,   0., 200.],
       [  0.,   0.,   0., ...,   0.,  -1.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,  -1.]])

#### Symbolic Sampling

In [11]:
# constraint function that can handle
# both explicit and symoblic adjacency matrix
def new_constraint(x, edges):
    """returns number of constraint violations"""
    sum_violations = 0
    for i, j in combinations(range(len(x)), 2):
        edge = edges[i, j]
        if (x[i] == 1 and x[j] == 1) and edge != 1:
            sum_violations += 1 - edge
    return sum_violations

In [12]:
# note that we could use this constraint
# the same way as before, with an explicit
# adjacency matrix
explicit_constraint = lambda x: new_constraint(x, edges)
# obtain explicit QUBO, same as above
qubo2, offset = SamplingCompiler.generate_qubo(
    cost_function, explicit_constraint, n, penalty_method="sum"
)
assert (qubo1 == qubo2).all()

In [13]:
from sympy import symbols
from autoqubo.symbolic import symbolic_matrix
from autoqubo.symbolic import insert_values


# create symbolic matrix
# use example graph to determine number of symbolic variables
symbolic_edges = symbolic_matrix(edges.shape[0], edges.shape[1])
# constraint is only dependent on graph size
constraint = lambda x: new_constraint(x, symbolic_edges)

In [14]:
# generate symbolic QUBO
symb_qubo, offset = SamplingCompiler.generate_qubo(
    cost_function, constraint, n, penalty_method="sum"
)

In [15]:
# symbolic QUBO has formulas as entries
symb_qubo

array([[-1.0, 200.0 - 200.0*s0 1, 200.0 - 200.0*s0 2, ...,
        200.0 - 200.0*s0 197, 200.0 - 200.0*s0 198, 200.0 - 200.0*s0 199],
       [0.0, -1.0, 200.0 - 200.0*s1 2, ..., 200.0 - 200.0*s1 197,
        200.0 - 200.0*s1 198, 200.0 - 200.0*s1 199],
       [0.0, 0.0, -1.0, ..., 200.0 - 200.0*s2 197, 200.0 - 200.0*s2 198,
        200.0 - 200.0*s2 199],
       ...,
       [0.0, 0.0, 0.0, ..., -1.0, 200.0 - 200.0*s197 198,
        200.0 - 200.0*s197 199],
       [0.0, 0.0, 0.0, ..., 0.0, -1.0, 200.0 - 200.0*s198 199],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, -1.0]], dtype=object)

In [16]:
# insert explicit values to obtain explicit QUBO
explicit_qubo = insert_values(symb_qubo, edges)

In [17]:
explicit_qubo

array([[ -1.,   0., 200., ..., 200., 200., 200.],
       [  0.,  -1.,   0., ..., 200., 200., 200.],
       [  0.,   0.,  -1., ..., 200., 200., 200.],
       ...,
       [  0.,   0.,   0., ...,  -1.,   0., 200.],
       [  0.,   0.,   0., ...,   0.,  -1.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,  -1.]])

In [18]:
# result is same as QUBO from explicit sampling
(explicit_qubo == qubo1).all()

True

## Runtime Comparison

In [19]:
from timeit import default_timer as timer

DATASET = BATCH_SMALL

In [20]:
# symbolic sampling
start_symb = timer()
# generate symbolic QUBO
symb_qubo, offset = SamplingCompiler.generate_qubo(
    cost_function, constraint, n, penalty_method="sum"
)
# insert explicit values to obtain explicit QUBO
for filename in DATASET:
    edges, n = read_graph(filename)
    explicit_qubo = insert_values(symb_qubo, edges)
stop_symb = timer()

Reading graph: c-fat200-1
Vertices: 200, Edges: 1534
Reading graph: c-fat200-2
Vertices: 200, Edges: 3235
Reading graph: brock200_1
Vertices: 200, Edges: 14834
Reading graph: brock200_2
Vertices: 200, Edges: 9876
Reading graph: brock200_3
Vertices: 200, Edges: 12048
Reading graph: san200_0.7_1
Vertices: 200, Edges: 13930
Reading graph: san200_0.7_2
Vertices: 200, Edges: 13930
Reading graph: san200_0.9_1
Vertices: 200, Edges: 17910
Reading graph: san200_0.9_2
Vertices: 200, Edges: 17910
Reading graph: san200_0.9_3
Vertices: 200, Edges: 17910


In [21]:
# explicit sampling
start_exp = timer()
# sample for each explicit QUBO
for filename in DATASET:
    edges, n = read_graph(filename)
    # explicit constraint function defined by given graph
    explicit_constraint = lambda x: old_constraint(x, edges)
    explicit_qubo, offset = SamplingCompiler.generate_qubo(
    cost_function, explicit_constraint, n, penalty_method="sum"
)
stop_exp = timer()

Reading graph: c-fat200-1
Vertices: 200, Edges: 1534
Reading graph: c-fat200-2
Vertices: 200, Edges: 3235
Reading graph: brock200_1
Vertices: 200, Edges: 14834
Reading graph: brock200_2
Vertices: 200, Edges: 9876
Reading graph: brock200_3
Vertices: 200, Edges: 12048
Reading graph: san200_0.7_1
Vertices: 200, Edges: 13930
Reading graph: san200_0.7_2
Vertices: 200, Edges: 13930
Reading graph: san200_0.9_1
Vertices: 200, Edges: 17910
Reading graph: san200_0.9_2
Vertices: 200, Edges: 17910
Reading graph: san200_0.9_3
Vertices: 200, Edges: 17910


In [22]:
symb_time = np.round(stop_symb - start_symb, 2)
exp_time = np.round(stop_exp - start_exp, 2)
print(f"Symbolic sampling took {symb_time}s in total.")
print(f"Explicit sampling took {exp_time}s in total.")
print(f"Symbolic sampling was {np.round(exp_time/symb_time, 2)}x faster for {len(DATASET)} instances.")


Symbolic sampling took 107.41s in total.
Explicit sampling took 563.05s in total.
Symbolic sampling was 5.24x faster for 10 instances.
